image: bitwalker/alpine-elixir:1.10.4
pipelines:
  default:
    - step:
        script:
          - mix local.hex --force
          - mix local.rebar --force
          - mix deps.get
          - apk add build-base
          - mix compile