image: srilaxmicars/build_deployment:1.0
pipelines:
  default:
    - step:
        script:
          - MIX_ENV=test mix deps.get
          - MIX_ENV=test mix ecto.create
          - MIX_ENV=test mix ecto.migrate
          - mix compile